pre-commit:
  commands:
    notebooktester:
      priority: 1
      glob: '*.ipynb'
      run: notebooktester notebooks -v -t 240
    clean-jupyter:
      priority: 2
      files: git ls-files
      glob: '*.ipynb'
      run: jupyter nbconvert --clear-output --inplace {staged_files}
      stage_fixed: true
    format:
      priority: 2
      files: git ls-files
      glob: '*.{py, ipynb}'
      run: ruff format {staged_files}
      stage_fixed: true
    ruff:
      priority: 2
      files: git ls-files
      glob: '*.py'
      run: ruff check {staged_files} --fix
    pyright:
      files: git ls-files
      glob: '*.py'
      run: pyright {staged_files}
    lychee:
      run: lychee . --suggest --max-concurrency 32 --cache --exclude toptal --format detailed --max-cache-age 7d

pre-merge:
  commands:
    notebooktester:
      glob: '*.ipynb'
      run: notebooktester notebooks -v -t 240
    format:
      glob: '*.{py, ipynb}'
      run: ruff format {all_files}
      stage_fixed: true
    clean-jupyter:
      glob: '*.ipynb'
      run: jupyter nbconvert --clear-output --inplace {all_files}
      stage_fixed: true
    ruff:
      glob: '*.py'
      run: ruff check {all_files} --fix
    pyright:
      glob: '*.py'
      run: pyright {staged_files}
    lychee:
      run: lychee . --suggest --max-concurrency 32 --cache --format detailed --max-cache-age 7d
